sensor_kit_base_link:
  camera0/camera_link:
    x: 0.10731
    y: 0.56343
    z: -0.27697
    roll: -0.025
    pitch: 0.315
    yaw: 1.035
  camera1/camera_link:
    x: -0.10731
    y: -0.56343
    z: -0.27697
    roll: -0.025
    pitch: 0.32
    yaw: -2.12
  camera2/camera_link:
    x: 0.10731
    y: -0.56343
    z: -0.27697
    roll: -0.00
    pitch: 0.335
    yaw: -1.04
  camera3/camera_link:
    x: -0.10731
    y: 0.56343
    z: -0.27697
    roll: 0.0
    pitch: 0.325
    yaw: 2.0943951
  camera4/camera_link:
    x: 0.07356
    y: 0.0
    z: -0.0525
    roll: 0.0
    pitch: -0.03
    yaw: -0.005
  camera5/camera_link:
    x: -0.07356
    y: 0.0
    z: -0.0525
    roll: 0.0
    pitch: -0.01
    yaw: 3.125
  rgb_front/camera_link:
    x: 2.0
    y: 0.0
    z: 2.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  rgb_view/camera_link:
    x: -4.5
    y: 0.0
    z: 2.8
    roll: 0.0
    pitch: 20.0
    yaw: 0.0
  semantic_segmentation_front/camera_link:
    x: 2.0
    y: 0.0
    z: 2.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  depth_front/camera_link:
    x: 2.0
    y: 0.0
    z: 2.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  dvs_front/camera_link:
    x: 2.0
    y: 0.0
    z: 2.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  traffic_light_right_camera/camera_link:
    x: 0.05
    y: -0.0175
    z: -0.1
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  traffic_light_left_camera/camera_link:
    x: 0.05
    y: 0.0175
    z: -0.1
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  lidar_base_link:
    x: 0.0
    y: 0.0
    z: 2.4
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  semantic_lidar_base_link:
    x: 0.0
    y: 0.0
    z: 2.4
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  radar_front_base_link:
    x: 2.0
    y: 0.0
    z: 2.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  lf_lidar_base_link:
    x: 0.3781
    y: 0.9413
    z: -0.411
    roll: -0.0072
    pitch: 0.3487865
    yaw: 1.11826
  lr_lidar_base_link:
    x: -1.9706
    y: 0.8573
    z: -0.4493
    roll: 0.0
    pitch: 0.3642
    yaw: 2.0264
  rf_lidar_base_link:
    x: 0.4479
    y: -0.8754
    z: -0.41259
    roll: -0.007819
    pitch: 0.36507
    yaw: -1.11247
  rr_lidar_base_link:
    x: -1.903
    y: -0.9566
    z: -0.4492
    roll: -0.004226
    pitch: 0.425127
    yaw: -1.96458
  front_lidar_base_link:
    x: 1.17075
    y: 0.061
    z: -1.5205
    roll: 0.0
    pitch: 0.0
    yaw: 0.0 
  gnss_link:
    x: 1.0
    y: 0.0
    z: 2.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  tamagawa/imu_link:
    x: 2.0
    y: 0.0
    z: 2.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

